- sku: 120P90
  name: "Google Home"
  price: 49.99
  stock: 10
- sku: 43N23P
  name: "Macbook Pro"
  price: 5399.99
  stock: 5
- sku: A304SD
  name: "Alexa Speaker"
  price: 109.50
  stock: 10
- sku: 234234
  name: "Raspberry Pi B"
  price: 30.
  stock: 2

